services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    network_mode: host
    restart: unless-stopped
    environment:
      - LIBVA_DRIVER_NAME=radeonsi
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    volumes:
      - /media/container-storage/plex/plex-config:/config
      - /media/container-storage/plex/temp:/transcode
      - /media/plexmedia:/data
