services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    network_mode: host
    restart: unless-stopped
    environment:
      - LIBVA_DRIVER_NAME=radeonsi
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /media/container-storage/plex/plex-config:/config
      - /media/plexmedia:/data
      - type: tmpfs
        target: /transcode
        tmpfs:
          size: 8gb

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_INCLUDE_STOPPED=false
